name = "placeholders-dev"
workers_dev = true
compatibility_date = "2022-04-22"
main = "./workers-site/index.js"
node_compat = true

[site]
bucket = "./public"

[env.staging]
name = "placeholders-staging"
workers_dev = true
node_compat = true

[env.production]
name = "placeholders"
workers_dev = false
routes = [
	{pattern = "placeholders.dev/*", zone_id = "51bfc6eeecc90565bd116ee3ebb5e3a8"},
	{pattern = "images.placeholders.dev/*", zone_id = "51bfc6eeecc90565bd116ee3ebb5e3a8"}
]
node_compat = true