name = "placeholders-dev"
workers_dev = true
compatibility_date = "2023-12-09"
compatibility_flags = ["nodejs_compat"]
main = "./src/index.ts"

[site]
bucket = "./public"

[env.staging]
name = "placeholders-staging"
workers_dev = true

[env.production]
name = "placeholders"
workers_dev = false
routes = [
	{pattern = "placeholders.dev/*", zone_id = "51bfc6eeecc90565bd116ee3ebb5e3a8"},
	{pattern = "images.placeholders.dev/*", zone_id = "51bfc6eeecc90565bd116ee3ebb5e3a8"}
]
logpush = true


analytics_engine_datasets = [
	{ binding = "PLACEHOLDERS_ANALYTICS" }
]
