name = "placeholders-dev"
account_id = "522ed7942a6ec29727e101623a48ea76"
workers_dev = true
compatibility_date = "2022-04-22"
main = "./workers-site/index.js"
node_compat = true

[site]
bucket = "./public"

[env.staging]
name = "placeholders-staging"
workers_dev = true
node_compat = true

[env.production]
name = "placeholders"
workers_dev = false
routes = [
	{pattern = "placeholders.dev/*", zone_name = "placeholders.dev"},
	{pattern = "images.placeholders.dev/*", zone_name = "placeholders.dev"}
]
node_compat = true